apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: rabbitmq
  labels:
    app: rabbitmq
    context: video-slicer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi