name: 'Provision AWS EKS Cluster using AWSCLI'

on: workflow_dispatch

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: 'terraform'
        sparse-checkout-cone-mode: false

    # This step is needed because expo-github-action does not support paths.
    # Therefore all mobile app assets should be moved to the project root.
    - name: Move terraform files to root
      run: |
        ls -lah
        shopt -s dotglob
        mv terraform/* .
        rm -rf terraform/eks
        rm -rf terraform/
        ls -lah

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Armazene essas credenciais nos secrets do repositório
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"
